server:
  port: 8092

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kafka.outboxconsumer.EventDeserializer
    topic: ${TOPIC:camel-relayer-topic}
    consumer-group: group1

  datasource:
    driver-classe-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_POST:3306}/${MYSQL_DB:camel}?allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mdymen_pass}
  jpa:
    show-sql: true
  main:
    allow-circular-references: true

  application:
    name: outbox-consumer
