server:
  port: 8100

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
    producer:
      bootstrap-servers: ${BOOSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kafka.relayerproducer.EventSerializer
    topic: ${TOPIC:relayer-topic}

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1

  application:
    name: relayer-producer

  log4j:
    logger:
      org:
        springframework:
          transaction: INFO


application:
  redis:
    enabled: false